name: Base check

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          npm ci

      - name: Run linter
        run: |
          make lint
